python main.py \
  --do_eval_along_training=True \
  --sup_cut=0.05 \
  --unsup_cut=0. \
  --unsup_ratio=0 \
  --shuffle_seed=42 \
  --train_batch_size=4 \
  --train_steps=100000 \
  --max_save=10 \
  --data_dir=data/processed_data \
  --model_dir=ckpt/5_supervised